# Generated by Django 4.2.25 on 2025-10-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SleepRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_date', models.DateField(verbose_name='Дата сна')),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Продолжительность сна (в часах)')),
                ('quality', models.IntegerField(choices=[(1, 'Очень плохо'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Качество сна')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Запись о сне',
                'verbose_name_plural': 'Записи о сне',
                'ordering': ['-sleep_date'],
            },
        ),
    ]
